// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vcopMyliISCTfk6VtjjbKuvAN439Tqw',
    appId: '1:169120728657:web:3437310e36d3b271a75a70',
    messagingSenderId: '169120728657',
    projectId: 'dynamic-ui-playground',
    authDomain: 'dynamic-ui-playground.firebaseapp.com',
    storageBucket: 'dynamic-ui-playground.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFR_y_u6r7icqwyGYKaipfC2ZRKj18P0',
    appId: '1:169120728657:android:1178a487db47e829a75a70',
    messagingSenderId: '169120728657',
    projectId: 'dynamic-ui-playground',
    storageBucket: 'dynamic-ui-playground.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZsZQehPI9IJEsCtaFcBcTKYbwgWyO3c',
    appId: '1:169120728657:ios:0d09210b931fcdbba75a70',
    messagingSenderId: '169120728657',
    projectId: 'dynamic-ui-playground',
    storageBucket: 'dynamic-ui-playground.firebasestorage.app',
    iosBundleId: 'com.example.dynamicUiPlayground',
  );
}
